version: '3.7'
services:
  noteapp-postgres:
    container_name: noteapp-postgres
    hostname: noteapp-postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: 'noteapp'
      POSTGRES_USER: 'noteapp'
      POSTGRES_PASSWORD: 'noteapp'
    ports:
      - 5441:5432

  noteapp-redis:
    container_name: noteapp-redis
    image: redis:6
    ports:
      - 6381:6379
