CREATE TABLE PUBLIC.NOTE (
  ID uuid NOT NULL DEFAULT uuid_generate_v4 (),
  TITLE text NOT NULL,
  CONTENT text NOT NULL,
  CONSTRAINT PK_NOTE PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.TAG (
  ID uuid NOT NULL DEFAULT uuid_generate_v4 (),
  LABEL text NOT NULL,
  CONSTRAINT PK_TAG PRIMARY KEY (ID),
  CONSTRAINT UK_TAG_LABEL UNIQUE (LABEL)
);

CREATE TABLE PUBLIC.NOTE_TAG (
  NOTE_ID uuid NOT NULL,
  TAG_ID uuid NOT NULL,
  CONSTRAINT PK_NOTE_TAG PRIMARY KEY (NOTE_ID, TAG_ID),
  CONSTRAINT FK_NOTE_TAG_NOTE FOREIGN KEY (NOTE_ID) REFERENCES PUBLIC.NOTE (ID),
  CONSTRAINT FK_NOTE_TAG_TAG FOREIGN KEY (TAG_ID) REFERENCES PUBLIC.TAG (ID)
);

